import { Header, Info, Project, Skills, AboutMe } from '@/components'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-white dark:bg-black relative'>
        <Header />
        <div className='dark:bg-zinc-900 bg-gray-200 min-h-screen w-screen pt-20 px-10'>
          <div className='fixed h-screen left-0 top-[5rem] w-[30%] px-3 text-gray-800 dark:text-gray-100 space-y-3 overflow-hidden pb-32'>
            <Info />
            <AboutMe />
          </div>
          <div className='w-[50%] mx-[30%]'>
            <div className='w-full space-y-10 pb-5'>
              <Project />
            </div>
          </div>
          <Skills />
        </div>
      </div>
    </>
  )
}
